class LurkType():
    MESSAGE = b'\x01'
    CHANGE_ROOM = b'\x02'
    FIGHT = b'\x03'
    PVPFIGHT = b'\x04'
    LOOT = b'\x05'
    START = b'\x06'
    ERROR = b'\x07'
    ACCEPT = b'\x08'
    ROOM = b'\x09'
    CHARACTER = b'\x0a'
    GAME = b'\x0b'
    LEAVE = b'\x0c'
    CONNECTION = b'\x0d'
    VERSION = b'\x0e'